---
- hosts: localhost
  roles:
    - provision-syslog-server

- hosts: syslog
  become: true
  roles:
   - configure-rsyslog

- hosts: localhost
  roles:
   - install-prerequisites
   - run-selenium-tests

- hosts: syslog
  become: true
  roles:
    - export-logs

#- hosts: localhost
#  roles:
#    - destroy-syslog-server
