---
#- hosts: syslog
#  become: true
#  roles:
#   - configure-rsyslog

- hosts: localhost
  become: true
  roles:
#   - install-prerequisites
   - run-selenium-tests

#- hosts: syslog
#  roles:
#    - export-logs

