---
- hosts: localhost
  tasks:

# provision syslog server
#    - name: Provision syslog server
#      shell: cd /Users/afaulkner/codes/terraform/syslog-server/aws && terraform apply -auto-approve
#      register: tfoutput
#    - debug: var=tfoutput

#    - name: Wait for syslog to provision
#      wait_for_connection:
#        sleep: 300 #wait for 5 minutes before moving on

    - name: Get terraform output
      shell: cd /Users/afaulkner/codes/terraform/syslog-server/aws && terraform output
      register: tfoutput
    - debug:
        var: tfoutput.stdout_lines[5] | select('match', '([\d.])') |  list | join()  #{{ list_vms.results | map(attribute='stdout') | list }}


# Get public IP of syslog server from task output
    - set_fact:
        syslogip: "{{tfoutput.stdout_lines[5] | join() }"
    - debug: var=syslogip
#
#    - name: Add host to inventory/host group 'syslog'
#      add_host:
#        name: "{{ syslogip }}"
#        groups: syslog


# run main playbook to run selenium tests, collect and parse logs
#    - name: Run selenium tests, collect and parse logs
#      shell: ansible-playbook -i hosts2.ini main.yml -v

# destroy syslog server
#    - name: Destroy syslog server
#      shell: cd /Users/afaulkner/codes/terraform/syslog-server/aws && terraform destroy -auto-approve
#      register: result
#    - debug: var=result
