---
- hosts: localhost
  vars_files:
    - group_vars/vars.yml
  roles:
    - provision-syslog-server

#- hosts: syslog
#  become: true
#  roles:
#   - configure-rsyslog

- hosts: localhost
  vars_files:
    - group_vars/vars.yml
  roles:
#   - install-prerequisites
   - run-selenium-tests

#- hosts: syslog
#  become: true
#  roles:
#    - export-logs

#- hosts: localhost
#  vars_files:
#    - group_vars/vars.yml
#  roles:
#    - destroy-syslog-server
