---
#- hosts: localhost
#  become: true
#  gather_facts: true
#  vars_files:
#    - group_vars/vars.yml
#  roles:
#    - {hosts: localhost, connection: local, role: install-prerequisites}
#    - {hosts: localhost, connection: local, role: run-selenium-tests}
#    - {hosts: syslog, role: log-collection}



- hosts: localhost
  connection: local
  roles:
    - install-prerequisities
    - run-selenium-tests

#- hosts: syslog
#  roles:
#    - log-collection

