---
- name: Run Selenium tests against Zero Client via AWI (headless)
##  shell: selenium-side-runner -c "goog:chromeOptions.args=[--headless,—nogpu] browserName=chrome" files/syslog_server.side.j2
  shell: python files/all-selenium-tests.py {{ip0}} {{ip1}} {{ip2}} {{ip3}}
  register: result

- debug: var=result


#- name: Test profile download from MC
#  shell: selenium-side-runner files/mc-profile-dl.side
#
#- name: Test connection to MC
#  shell: selenium-side-runner files/mc-connect.side
#
#- name: Test blocked scancode feature (upcoming feature)
#  shell: selenium-side-runner files/scancode.side

#Certificate tests:
#  - no cert
#  - incorrect cert
#  - expired cert
#

# Run all tests in parallel in multiple browser windows, spread across all cores available on machine
#- name: Run all Selenium tests in parallel
#  shell: selenium-side-runner files/*.side