---
#Linux
# - name: Use Python3
#   shell: sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1
#   when: ansible_distribution == "CentOS" or ansible_distribution == "Ubuntu"

# - name: Install nodejs on Linux
#   shell: curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
#   when: ansible_distribution == "CentOS" or ansible_distribution == "Ubuntu"

- name: Install prereqs on Linux
  package:
    name: "{{item}}"
    state: present
  with_items:
    - nodejs
    - python-apt
    - default-jdk
    - xvfb # X virtual framebuffer - run chrome headlessly
    - python3-pip
    - google-chrome-stable
  when: ansible_distribution == "CentOS" or ansible_distribution == "Ubuntu"

# - name: Install npm and dependencies
#   shell: sudo npm install npm-install-all -g
#   when: ansible_distribution == "CentOS" or ansible_distribution == "Ubuntu"

# - name: Install selenium-side-runner
#   shell: sudo npm install -g selenium-side-runner
#   when: ansible_distribution == "CentOS" or ansible_distribution == "Ubuntu"

# - name: Install dependencies via pip
#   shell: pip3 install pytest selenium pyvirtualdisplay virtualenv
#   when: ansible_distribution == "CentOS" or ansible_distribution == "Ubuntu"

- name: Install browser driver for Chrome
  unarchive:  
    src: https://chromedriver.storage.googleapis.com/86.0.4240.22/chromedriver_linux64.zip
    dest: /usr/local/share/
    remote_src: yes
    mode: 766
  when: ansible_distribution == "CentOS" or ansible_distribution == "Ubuntu"

- name: Symlink Chromedriver to bin dir
  become: true
  shell: sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  when: ansible_distribution == "CentOS" or ansible_distribution == "Ubuntu"

#Mac
- name: Verify Homebrew is installed
  stat:
    path: /usr/local/bin/brew
  register: homebrew_check
  when: ansible_distribution != "CentOS" or ansible_distribution != "Ubuntu"

- name: Install nodejs on MacOS
  homebrew:
    name: node
    state: present
  register: result
  until: result is successful
  when: homebrew_check.stat.exists

- name: Install selenium
  shell: npm install -g selenium-side-runner
  when: homebrew_check.stat.exists

- name: Install browser driver for Chrome
  unarchive:
    src: https://chromedriver.storage.googleapis.com/86.0.4240.22/chromedriver_mac64.zip
    dest: /usr/local/bin/
    remote_src: yes
    mode: 766
  when: homebrew_check.stat.exists