# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.common.exceptions import NoSuchElementException, TimeoutException


# login
driver = webdriver.Chrome()
driver.get("https://192.168.0.108/login.html")
driver.set_window_size(1440, 877)
driver.find_element(By.ID, "login").click()

# assign syslog server
driver.get("https://192.168.0.108/diagnostics/event_log.html")
element = driver.find_element(By.NAME, "syslog_host0")
actions = ActionChains(driver)
actions.double_click(element).perform()
driver.find_element(By.NAME, "syslog_host0").click()
driver.find_element(By.NAME, "syslog_host0").send_keys("2")
driver.find_element(By.NAME, "syslog_host1").click()
driver.find_element(By.NAME, "syslog_host1").send_keys("2")
driver.find_element(By.NAME, "syslog_host2").click()
driver.find_element(By.NAME, "syslog_host2").send_keys("2")
driver.find_element(By.NAME, "syslog_host3").click()
driver.find_element(By.NAME, "syslog_host3").send_keys("2")
driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) input:nth-child(2)").click()
driver.find_element(By.NAME, "continue_button").click()

# enable and configure ntp
driver.get("https://192.168.0.108/configuration/time.html")
driver.find_element(By.NAME, "enable_ntp").click()
driver.find_element(By.CSS_SELECTOR, "tr:nth-child(4) input:nth-child(2)").click()
driver.find_element(By.NAME, "ntp_dns_name").click()
driver.find_element(By.NAME, "ntp_dns_name").send_keys("pool.ntp.org")
driver.find_element(By.ID, "time_zone_offset").click()
dropdown = driver.find_element(By.ID, "time_zone_offset")
dropdown.find_element(By.XPATH, "//option[. = '(UTC-8:00) America/Vancouver']").click()
driver.find_element(By.CSS_SELECTOR, "tr:nth-child(14) input:nth-child(2)").click()
driver.find_element(By.CSS_SELECTOR, "#continue_button > table").click()
driver.find_element(By.CSS_SELECTOR, "#continue_button > table").click()
driver.find_element(By.NAME, "continue_button").click()
# disable ntp
driver.find_element(By.NAME, "enable_ntp").click()
driver.find_element(By.CSS_SELECTOR, "tr:nth-child(14) input:nth-child(2)").click()
driver.find_element(By.CSS_SELECTOR, "#continue_button > table").click()
driver.find_element(By.CSS_SELECTOR, "#continue_button > table").click()
driver.find_element(By.NAME, "continue_button").click()


# logout
driver.find_element(By.LINK_TEXT, "Log Out").click()
driver.close()

