---
- name: Install Python, awscli
  package:
    name: "{{item}}"
    state: present
  with_items:
    - python
    - awscli

# Send python file to syslog server
- name: Add parsing script to syslog server
  copy:
    src: files/parse-logs.py
    dest: /var/log/zero-client/
    owner: syslog
    group: syslog
    mode: 0774

# Run python file to parse the logs for ntp log lines (output should be sent to a new file)
- name: Run parsing script
  shell: cd /var/log/zero-client/ && sudo python parse-logs.py

- name: Archive the syslog file
  archive: 
    path: 
    - /var/log/zero-client/zero-client.log
    - /var/log/zero-client/parsed.txt
    dest: /var/log/zero-client/zero-client-log.zip
    format: zip

- name: Export Zero Client syslogs to AWS S3
  shell: aws s3 cp /var/log/zero-client/zero-client-log.zip s3://af-syslogs/auto-syslog/

# add time delay before tf destroy role
- name: Wait for 1 minute before ending playbook
  wait_for:
    delay: 60 # delay playbook for 60 seconds
    timeout: 0 # timeout after 0 seconds



